/**:
  /move_base*:
    ros__parameters:
      TrajectoryPlannerROS:

      # Robot Configuration Parameters
        max_vel_x: 0.18
        min_vel_x: 0.08

        max_vel_theta:  1.0
        min_vel_theta: -1.0
        min_in_place_vel_theta: 1.0

        acc_lim_x: 1.0
        acc_lim_y: 0.0
        acc_lim_theta: 0.6

      # Goal Tolerance Parameters
        xy_goal_tolerance: 0.10
        yaw_goal_tolerance: 0.05

      # Differential-drive robot configuration
        holonomic_robot: false

      # Forward Simulation Parameters
        sim_time: 0.8
        vx_samples: 18
        vtheta_samples: 20
        sim_granularity: 0.05
        
      DWBPlannerROS:

      # Robot Configuration Parameters
        max_vel_x: 0.22
        min_vel_x: -0.22

        max_vel_y: 0.0
        min_vel_y: 0.0

      # The velocity when robot is moving in a straight line
        max_trans_vel:  0.22
        min_trans_vel:  0.11

        max_rot_vel: 2.75
        min_rot_vel: 1.37

        acc_lim_x: 2.5
        acc_lim_y: 0.0
        acc_lim_theta: 3.2 

      # Goal Tolerance Parametes
        xy_goal_tolerance: 0.05
        yaw_goal_tolerance: 0.17
        latch_xy_goal_tolerance: false

      # Forward Simulation Parameters
        sim_time: 1.5
        vx_samples: 20
        vy_samples: 0
        vth_samples: 40
        controller_frequency: 10.0

      # Trajectory Scoring Parameters
        path_distance_bias: 32.0
        goal_distance_bias: 20.0
        occdist_scale: 0.02
        forward_point_distance: 0.325
        stop_time_buffer: 0.2
        scaling_speed: 0.25
        max_scaling_factor: 0.2

      # Oscillation Prevention Parameters
        oscillation_reset_dist: 0.05

      # Debugging
        publish_traj_pc : true
        publish_cost_grid_pc: true
        
      global_costmap:
        global_frame: map
        robot_base_frame: base_footprint

        update_frequency: 10.0
        publish_frequency: 10.0
        transform_tolerance: 0.5

        static_map: true
      
      local_costmap:
        global_frame: odom
        robot_base_frame: base_footprint

        update_frequency: 10.0
        publish_frequency: 10.0
        transform_tolerance: 0.5  

        static_map: false  
        rolling_window: true
        width: 3
        height: 3
        resolution: 0.05
        
      shutdown_costmaps: false
      controller_frequency: 10.0
      planner_patience: 5.0
      controller_patience: 15.0
      conservative_reset_dist: 3.0
      planner_frequency: 5.0
      oscillation_timeout: 10.0
      oscillation_distance: 0.2

      obstacle_range: 3.0
      raytrace_range: 3.5

      footprint: [[-0.105, -0.105], [-0.105, 0.105], [0.041, 0.105], [0.041, -0.105]]
      #robot_radius: 0.105

      inflation_radius: 0.55
      cost_scaling_factor: 10.0

      map_type: costmap
      observation_sources: scan
      scan: {sensor_frame: base_scan, data_type: LaserScan, topic: scan, marking: true, clearing: true}

